version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: yaci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foobar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgREST API
  postgrest:
    image: postgrest/postgrest:v11.2.0
    environment:
      PGRST_DB_URI: postgres://postgres:foobar@postgres:5432/yaci
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: postgres
      PGRST_SERVER_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "3010:3000"
    depends_on:
      postgres:
        condition: service_healthy

  # Yaci Indexer
  yaci:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    command: |
      extract postgres localhost:9090
      -p postgres://postgres:foobar@localhost:5432/yaci
      --live
      -k
      --enable-prometheus
      --enable-denom-resolver
    environment:
      YACI_LOGLEVEL: info
    ports:
      - "2112:2112"  # Prometheus metrics
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Block Explorer UI
  explorer:
    build:
      context: ./explorer-next
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:foobar@postgres:5432/yaci
      POSTGREST_URL: http://postgrest:3000
      NEXT_PUBLIC_POSTGREST_URL: http://localhost:3010
      CHAIN_ID: manifest-1
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - postgrest
      - yaci
    restart: unless-stopped

  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:

networks:
  default:
    name: yaci-explorer-network